
workflows:
  university-dashboard:
    name: university dashboard
    instance_type: mac_mini_m1
    max_build_duration: 100
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.9.1
      node: 12.14.0
      npm: 6.13.7
      java: 11
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: get flutter packages
        script: flutter packages pub get
      - name: build apk
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - jafarsadaq511@gmail.com
